version: "3.9"

services:
  app:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.app
    container_name: pw_backend_app
    env_file:
      - ../../.env
    depends_on:
      - db
      - s3
    ports:
      - "8000:8000"
    volumes:
      - ../..:/app

  db:
    image: postgres:16
    container_name: pw_backend_db
    environment:
      POSTGRES_USER: pw_manager
      POSTGRES_PASSWORD: pw_manager_password
      POSTGRES_DB: pw_manager_dev
    ports:
      - "5432:5432"
    volumes:
      - pw_pgdata:/var/lib/postgresql/data

  s3:
    image: minio/minio
    container_name: pw_backend_s3
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: dev-access-key
      MINIO_ROOT_PASSWORD: dev-secret-key
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - pw_s3data:/data

volumes:
  pw_pgdata:
  pw_s3data:


